CXX=g++

ex18: ex18.cpp MyFirstAbstractClass.h MyFirstAbstractClass.cpp MyFirstChildClass.h MyFirstChildClass.cpp
	$(CXX) ex18.cpp MyFirstAbstractClass.cpp MyFirstChildClass.cpp -o ex18

clean:
	rm -f ex18 *~
